### ISSUE TITLE
Release geoparser 0.1.2

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/geoparser#14]
Prepare for release: 

* [x] Tackle #11
* [x] `devtools::check()` 
* [x] `rhub::check_for_cran()`  
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
 
Submit to CRAN: 
 
* [x] Update `cran-comments.md` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()`

**Comment by maelle** [comment]
@koheiw the new version is on CRAN, thanks again for the bug fix, and see you soon in the repo. :wink:

**Comment by koheiw** [comment]
Thanks too!
