### ISSUE TITLE
Seems like geoparser is down

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/geoparser#15]
no rush @maelle  - for when you get back. 

was updating the webservices task view and noticed that the url for the description of this package lead to a 404. maybe they are just temporarily down?

**Comment by maelle** [comment]
Indeed, thanks!

@charlieg geoparser.io is no longer available, correct?

**Comment by maelle** [comment]
I've requested CRAN to archive the package, and am about to archive this repo. Thanks again @sckott.
